import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  const current_year = new Date().getFullYear();

  return (
    <div className={styles.container}>
      <Head>
        <title>Jeremy Fields</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.intro}>
          <h1>Jeremy Fields</h1>
            Data Scientist at <a href="https://about.bgov.com/" target="_blank">@Bloomberg</a>
            <br/>
            <a href="https://delafields.github.io/" target="_blank">👉 data portfolio</a>
        </div>
        <div className={styles.links}>
          <a href="https://www.github.com/delafields" target="_blank">IRL projects</a>
          <br/>
          <a href="https://www.twitter.com/delafields" target="_blank">Bird app</a>
          <br/>
          <a href="https://www.github.com/delafields" target="_blank">Github</a>
        </div>
        {/* <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div> */}
      </main>
      <div className={styles.foot}>
        <p>Jeremy Fields {current_year}</p>
        <p>Made in the U.S.A.</p>
      </div>
    </div>
  )
}
